<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SeriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cosplay_series = [
            "Naruto",
            "Dragon Ball",
            "One Piece",
            "Shingeki no Kyojin (Attack on Titan)",
            "Boku no Hero Academia (My Hero Academia)",
            "Sailor Moon",
            "Pokémon",
            "Death Note",
            "Bleach",
            "Tokyo Ghoul",
            "Fairy Tail",
            "Fullmetal Alchemist",
            "Kimetsu no Yaiba (Demon Slayer)",
            "One Punch Man",
            "Sword Art Online",
            "Neon Genesis Evangelion",
            "JoJo no Kimyou na Bouken (JoJo's Bizarre Adventure)",
            "Hunter x Hunter",
            "Kuroshitsuji (Black Butler)",
            "Tengen Toppa Gurren Lagann",
            "Persona",
            "Shigatsu Wa Kimi No Uso (Your Lie in April)",
            "Suzumiya Haruhi no Yuuutsu (The Melancholy of Haruhi Suzumiya)",
            "Vocaloid",
            "Fate Series",
            "Love Live!",
            "Code Geass",
            "Steins;Gate",
            "Gundam",
            "Berserk",
            "Trigun",
            "Final Fantasy",
            "Kingdom Hearts",
            "Valorant",
            "League of legends",
            "Fire Emblem",
            "Metal Gear Solid",
            "Resident Evil",
            "Tales Series",
            "Monster Hunter",
            "Dark Souls",
            "Bayonetta",
            "Devil May Cry",
            "Touhou Project",
            "Super Mario",
            "The Legend of Zelda",
            "Metroid",
            "Splatoon",
            "Animal Crossing",
            "Yakuza",
            "Danganronpa",
            "Mega Man",
            "Castlevania",
            "Silent Hill",
            "Ace Attorney",
            "Ni no Kuni",
            "Nier",
            "DOTA 2",
            "Nikke",
            "Wuthering Waves",
            "Genshin Impact",
            "Honkai Star Rail",
            "Honkai Impact",
            "Blue Archive",
            "Azur Lane",
            "Arknight",
            "Mobile Legends",
            "Dragon Quest",
            "Shin Megami Tensei",
            "Bravely Default",
            "Assassin's Creed",
            "The Witcher",
            "Halo",
            "God of War",
            "Uncharted",
            "Mass Effect",
            "Red Dead Redemption",
            "Call of Duty",
            "Grand Theft Auto",
            "The Elder Scrolls",
            "BioShock",
            "Gears of War",
            "Destiny",
            "Borderlands",
            "Fallout",
            "Tomb Raider",
            "Mortal Kombat",
            "Street Fighter",
            "Game of Thrones",
            "Harry Potter",
            "Lord of the Rings",
            "Marvel",
            "DC Comics",
            "Star Wars",
            "The Walking Dead",
            "Doctor Who",
            "Sherlock",
            "Breaking Bad",
            "Stranger Things",
            "Black Panther",
            "Wonder Woman",
            "Spider-Man",
            "Batman",
            "Superman",
            "Iron Man",
            "Thor",
            "Captain America",
            "Deadpool",
            "X-Men",
            "The Simpsons",
            "Family Guy",
            "Rick and Morty",
            "South Park",
            "The Office",
            "Friends",
            "Sen to Chihiro no Kamikakushi (Spirited Away)",
            "Akira",
            "Cowboy Bebop",
            "Studio Ghibli",
            "Tonari no Totoro (My Neighbor Totoro)",
            "Mononoke Hime (Princess Mononoke)",
            "Howl's Moving Castle",
            "Kiki's Delivery Service",
            "Kimi no Na wa. (Your Name)",
            "Ghost in the Shell",
            "Grave of the Fireflies",
            "Tenki no Ko (Weathering with You)",
            "Koe no Katachi (A Silent Voice)",
            "Kaze no Tani no Nausicaä (Nausicaä of the Valley of the Wind)",
            "Kurenai no Buta (Porco Rosso)",
            "Ponyo",
            "Mimi wo Sumaseba (Whisper of the Heart)",
            "Kaze Tachinu (The Wind Rises)",
            "Omoide Poroporo (Only Yesterday)",
            "Karigurashi no Arrietty (The Secret World of Arrietty)",
            "From Up on Poppy Hill",
            "When Marnie Was There",
            "Neko no Ongaeshi (The Cat Returns)",
            "Heisei Tanuki Gassen Ponpoko (Pom Poko)",
            "Umi ga Kikoeru (Ocean Waves)",
            "Houhokekyo Tonari no Yamada-kun (My Neighbors the Yamadas)",
            "Ongaku (On-Gaku: Our Sound)",
            "Nakitai Watashi wa Neko wo Kaburu (A Whisker Away)",
            "Penguin Highway",
            "Kaijuu no Kodomo (Children of the Sea)",
            "Ride Your Wave",
            "Momo e no Tegami (A Letter to Momo)",
            "Bakemono no Ko (The Boy and the Beast)",
            "Mirai no Mirai (Mirai)",
            "Yoake Tsugeru Lu no Uta (Lu over the Wall)",
            "Tokyo Godfathers",
            "Mary to Majo no Hana (Mary and the Witch's Flower)",
            "Promare",
            "Sayonara no Asa ni Yakusoku no Hana wo Kazarou (Maquia: When the Promised Flower Blooms)",
            "Redline",
            "Metropolis",
            "Perfect Blue",
            "Juubee Ninpuuchou (Ninja Scroll)",
            "Hotaru no Haka (Grave of the Fireflies)",
            "Papurika (Paprika)",
            "Toki wo Kakeru Shoujo (The Girl Who Leapt Through Time)",
            "Koukaku Kidoutai (Ghost in the Shell)",
            "Ookami Kodomo no Ame to Yuki (Wolf Children)",
            "Summer Wars",
            "Kokoro ga Sakebitagatterunda. (The Anthem of the Heart)",
            "Kaguya-hime no Monogatari (The Tale of the Princess Kaguya)",
            "Stranger: Mukou Hadan (Sword of the Stranger)",
            // New
            "Hololive",
            "Nijisanji",
            "Gamers!",
            "VSPO",
            'MAHA 5',
            "Jujutsu Kaisen",
            "Tokyo Revengers",
            "To Your Eternity (Fumetsu no Anata e)",
            "That Time I Got Reincarnated as a Slime (Tensei shitara Slime Datta Ken)",
            "Fruits Basket",
            "Horimiya (Hori To Miyamura-kun)",
            "Kaguya Sama: Love is war",
            "Bocchi The Rock",
            "Mushoku Tensei: Jobless Reincarnation",
            "The Promised Neverland Season 2 (Yakusoku no Neverland)",
            "Dr Stone: Stone Wars)",
            "Re:Zero (Re:Zero kara Hajimeru Isekai Seikatsu)",
            "The Seven Deadly Sins: Dragon's Judgement (Nanatsu no Taizai: Fundo no Shinpan)",
            "Beastars",
            "Sk8 the Infinity",
            "Cells at Work!! (Hataraku Saibou)",
            "Non Non Biyori Nonstop",
            "Wonder Egg Priority",
            "Bottom-tier Character Tomozaki (Jaku-Chara Tomozaki-kun)",
            "So I'm a Spider, So What? (Kumo desu ga, Nani ka?)",
            "Log Horizon: Destruction of the Round Table (Log Horizon: Entaku Houkai)",
            "Kemono Jihen",
            "Hortensia Saga (Hortensia Saga)",
            "Heaven's Design Team (Tenchi Souzou Design-bu)",
            "Yuru Camp",
            "Haikyuu",
            "Kuroko no basuke (Kuroko no basketball)",
            "The Quintessential Quintuplets (go toubun no Hanayome)",
            "The Hidden Dungeon Only I Can Enter (Ore dake Haireru Kakushi Dungeon)",
            "World Trigger Season 2 (World Trigger 2nd Season)",
            "Redo of Healer (Kaifuku Jutsushi no Yarinaoshi)",
            "The Idaten Deities Know Only Peace (Heion Sedai no Idaten-tachi)",
            "Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari",
            "The Case Study of Vanitas (Vanitas no Carte)",
            "Suppose a Kid from the Last Dungeon Boonies Moved to a Starter Town (Tatoeba Last Dungeon Mae no Mura no
            Shounen ga Joban no Machi de Kurasu Youna Monogatari)",
            "World Witches: Take Off!",
            "2.43: Seiin High School Boys Volleyball Team (2.43: Seiin Koukou Danshi Volley-bu)",
            "Back Arrow (Back Arrow)",
            "Heike Monogatari (Heike Monogatari)",
            "Hori-san to Miyamura-kun (Horimiya)",
            "I Chu: Halfway Through the Idol (I Chu: Halfway Through the Idol)",
            "Idoly Pride (Idoly Pride)",
            "Kai Byoui Ramune (Kai Byoui Ramune)",
            "Spy x Family",
        ];

        $now = Carbon::now();

        foreach ($cosplay_series as $cos) {
            DB::table('series')->insert([
                'series' => $cos,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}